### ISSUE TITLE
Mod recipe conflicts - Water Strainer

### ISSUE THREAD

**Issue by ghost** [FiveEYZ/PreedCraft#1]
The water strainer mod has to conflicting recipes.

Net is three strings in a vertical line in the center of the 3x3 crafting grid, this should give the net, but it gives fuse from Steves Carts instead.

Garden Trowel is the same recipe as an iron chisel, from the chisel mod, and it overrules the Garden Trowel so you get a chisel instead.

No other conflicting recipes found so far with Water Strainer.

**Comment by FiveEYZ** [comment]
Net will be changed to:
[![Screenshot from Gyazo](https://gyazo.com/ba758e63c670b2e2c1dadba269bd5b70/raw)](https://gyazo.com/ba758e63c670b2e2c1dadba269bd5b70)

Garden Trowel will be changed to:
[![Screenshot from Gyazo](https://gyazo.com/f91c302c0cff67a47414013fefe0f489/raw)](https://gyazo.com/f91c302c0cff67a47414013fefe0f489)

Other suggestions for recipe fix are welcome.

**Comment by ghost** [comment]
Super good 👍

**Comment by FiveEYZ** [comment]
fixed in PreedCraft 2.0.4
